### ISSUE TITLE
Error when getting artifacts from s3 in pipelines UI

### ISSUE THREAD

**Issue by zemarx** [argoflow/argoflow-aws#134]
Here are logs from `ml-pipeline-ui-artifact`

```
GET /pipeline/artifacts/get?source=s3&peek=256&bucket=xxxxxxxxxxxxxx&key=pipelines%2Fartifacts%2Fconditional-execution-pipeline-with-exit-handler-9kt8r%2Fconditional-execution-pipeline-with-exit-handler-9kt8r-1986841581%2Fflip-coin-op-Output.tgz
Getting storage artifact at: s3: xxxxxxxxxxxxxx/pipelines/artifacts/conditional-execution-pipeline-with-exit-handler-9kt8r/conditional-execution-pipeline-with-exit-handler-9kt8r-1986841581/flip-coin-op-Output.tgz
GET /pipeline/artifacts/get?source=s3&peek=256&bucket=xxxxxxxxxxxxxx&key=pipelines%2Fartifacts%2Fconditional-execution-pipeline-with-exit-handler-9kt8r%2Fconditional-execution-pipeline-with-exit-handler-9kt8r-1986841581%2Fmain.log
Getting storage artifact at: s3: xxxxxxxxxxxxxx/pipelines/artifacts/conditional-execution-pipeline-with-exit-handler-9kt8r/conditional-execution-pipeline-with-exit-handler-9kt8r-1986841581/main.log
Unable to fetch credentials from AWS metadata store: FetchError: invalid json response body at http://169.254.169.254/latest/meta-data/iam/security-credentials/upstream%20connect%20error%20or%20disconnect/reset%20before%20headers.%20reset%20reason:%20connection%20failure reason: Unexpected token u in JSON at position 0
unable to get credentials from AWS metadata store.
Unable to fetch credentials from AWS metadata store: FetchError: invalid json response body at http://169.254.169.254/latest/meta-data/iam/security-credentials/upstream%20connect%20error%20or%20disconnect/reset%20before%20headers.%20reset%20reason:%20connection%20failure reason: Unexpected token u in JSON at position 0
unable to get credentials from AWS metadata store.
S3Error: Access Denied
    at Object.parseError (/server/node_modules/minio/dist/main/xml-parsers.js:86:11)
    at /server/node_modules/minio/dist/main/transformers.js:156:22
    at DestroyableTransform._flush (/server/node_modules/minio/dist/main/transformers.js:80:10)
    at DestroyableTransform.prefinish (/server/node_modules/readable-stream/lib/_stream_transform.js:138:10)
    at DestroyableTransform.emit (events.js:223:5)
    at prefinish (/server/node_modules/readable-stream/lib/_stream_writable.js:619:14)
    at finishMaybe (/server/node_modules/readable-stream/lib/_stream_writable.js:627:5)
    at endWritable (/server/node_modules/readable-stream/lib/_stream_writable.js:638:3)
    at DestroyableTransform.Writable.end (/server/node_modules/readable-stream/lib/_stream_writable.js:594:41)
    at IncomingMessage.onend (_stream_readable.js:693:10) {
  code: 'AccessDenied',
  requestid: 'J9KMA29NKC0KYR4X',
  hostid: 'xM7au1X2I91zu05g3vheRsg3g0zBLOnmVUzn8WqwidvnJMqtyo2jQtUJZPeWh1R6sL55PMlxp7A=',
  amzRequestid: null,
  amzId2: null,
  amzBucketRegion: null
}
```

Still artifcats are saved successfully to the s3 bucket and pipelines are running without problem.

**Comment by DavidSpek** [comment]
@zemarx When did you do your deployment? We pushed an update for the Pipelines deployment yesterday that should address this issue. When we were running into it the access denied error, the cause was a mistake in the AWS policies.

**Comment by zemarx** [comment]
I did it yesterday after the merge of 'feature/kfp testing' pr. But maybe i'm missing something or something hasn't updated properly, because i deployed it after trying to deploy master before those changes, so it wasn't a fresh install.

**Comment by zemarx** [comment]
Still no luck. Maybe something with metadata endpoint `http://169.254.169.254/latest/meta-data/iam/security-credentials/...`? It seems that it doesn't return the necessary data or even returns error. I've tried googling it (https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/instancedata-data-retrieval.html), but still not sure what is the problem, maybe i have to do something with ec2 worker instances of the cluster?

**Comment by zemarx** [comment]
I now got it working, i have an autoscaling node group created for eks cluster and i had to add s3 permissions to that autoscaling group role
